### ISSUE TITLE
Energy Consumption Entities for Washer and Dryer Unknown or Unavailable 

### ISSUE THREAD

**Issue by chrestme** [astrandb/miele#109]
### The problem

First, thanks so much for developing this integration.

The issue I am having is the energy consumption entities for both a washing machine and tumble dryer device are not updating correctly. The values are either 0.0 or 'unknown'. It appears the devices sometimes report the energy consumption as 'unknown' when they are actually running a program, i.e. when the values should be non-zero.

I used the blueprint provided in the readme to add some logging for the energy consumption entities. They are attached.

Thanks again.

### Version of miele integration having the issue?

0.0.22

### Version of Home Assistant Core having the issue?

2022.5.4

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.system_log.external
Source: components/system_log/__init__.py:190
Integration: System Log (documentation, issues)
First occurred: June 13, 2022 at 8:00:33 PM (12 occurrences)
Last logged: June 14, 2022 at 4:27:07 PM

Miele status: sensor.washing_machine_energy_consumption: unavailable | {'state_class': <SensorStateClass.TOTAL_INCREASING: 'total_increasing'>, 'unit_of_measurement': 'kWh', 'device_class': 'energy', 'friendly_name': 'Washing machine Energy Consumption'}
Miele status: sensor.tumble_dryer_energy_consumption: unknown | {'state_class': <SensorStateClass.TOTAL_INCREASING: 'total_increasing'>, 'unit_of_measurement': 'kWh', 'device_class': 'energy', 'friendly_name': 'Tumble dryer Energy Consumption'}
Miele status: sensor.washing_machine_energy_consumption: unknown | {'state_class': <SensorStateClass.TOTAL_INCREASING: 'total_increasing'>, 'unit_of_measurement': 'kWh', 'device_class': 'energy', 'friendly_name': 'Washing machine Energy Consumption'}
Miele status: sensor.washing_machine_energy_consumption: 0.0 | {'state_class': <SensorStateClass.TOTAL_INCREASING: 'total_increasing'>, 'unit_of_measurement': 'kWh', 'device_class': 'energy', 'friendly_name': 'Washing machine Energy Consumption'}
Miele status: sensor.tumble_dryer_energy_consumption: 0.0 | {'state_class': <SensorStateClass.TOTAL_INCREASING: 'total_increasing'>, 'unit_of_measurement': 'kWh', 'device_class': 'energy', 'friendly_name': 'Tumble dryer Energy Consumption'}
```

**Comment by ACrazyConcept** [comment]
I think I have the same issue with a washing machine. The energy consumption is unknown when the machine is not in operation. IT appears that the API just simply returns null. Maybe there should be a default value of "0" set when ecoFeedback returns null.

**Comment by stefan-schoene** [comment]
I noticed the same thing regarding the state 'unkown' when the appliance is not running. 
When running my washing machine (WWD660) always shows 0,0 kWh, whereas the dryer (TWF760WP) shows the energy consumption.

The JSON export from HA settings shows the following information for the dryer:
<img width="415" alt="Bildschirm­foto 2022-09-02 um 14 21 24" src="https://user-images.githubusercontent.com/78681069/188141670-370c3261-5237-4cfc-96d6-8fda374ac1e5.png">

The washing machine responds with "null" for ecofeedback:
<img width="359" alt="Bildschirm­foto 2022-09-02 um 14 21 59" src="https://user-images.githubusercontent.com/78681069/188141775-fe9aa342-c1d6-44c0-bceb-dea4840dda4d.png">

Apparently the function "ecoFeedback" https://www.miele.de/haushalt/1563.htm?info=200020182-ZPV is necessary for the appliance to show the usage, so it might make sense to aways show "unkown" lif the API response is "null" instead of "0,0 kWh" during a run.

**Comment by gschmidl** [comment]
I'm getting something similar for the WCE670. I had to manually activate the energy and water consumption sensors (they worked with the "old" integration) and the energy dashboard is showing:

```
statistics_not_defined
  sensor.washing_machine_energy_consumption
Entity not available
The status of this configured entity is currently not available:
sensor.washing_machine_energy_consumption (unknown)
``` 

sensor.washing_machine_water_consumption does not show up in the energy dashboard as a source.

**Comment by astrandb** [comment]
> sensor.washing_machine_water_consumption does not show up in the energy dashboard as a source

@gschmidl This is a new feature in HA 2022.11.0 Fixed and will be released soon.
