### ISSUE TITLE
Water Sensor reporting wrong value

### ISSUE THREAD

**Issue by AtrejaAlwinnen** [astrandb/miele#274]
### The problem

Hi,
i have a G7160 Dishwasher and a WCI870 Whasing maschine and the same problem with both.
When the washing machine or dishwasher starts, the water consumption sensor briefly indicates a water consumption of 8L, then it drops to 0L and then begins to transmit the actual consumption. 
The 8L are then added to the total consumption in the Energy Dashboard.

Thx in advance

### Version of miele integration having the issue?

miele-v0.1.13

### Version of Home Assistant Core having the issue?

Home Assistant 2023.5.3

### Additional information

![waterconsumption](https://github.com/astrandb/miele/assets/72468128/a14d68a2-0d5f-45dd-984c-50c02161f5ec)

**Comment by astrandb** [comment]
Well, it is not clear what is happening here. Is it always 8 as initial spike? Or is the 8 the last value from previous washing session? The sensor just displays the value that is read from the API.

**Comment by AtrejaAlwinnen** [comment]
It is always the same 8L spike on both machines. No matter what the last sensor reading was.
![waterconsumption2](https://github.com/astrandb/miele/assets/72468128/7c530783-bef8-4920-9d8c-9183425199e2)

**Comment by astrandb** [comment]
That's odd. I also have a WCI870 but it shows no spikes.
![image](https://github.com/astrandb/miele/assets/5016010/eb6212af-1c05-499e-80f2-0a41a0c381ce)

There is no obvious reason that the sensor should show anything else than what is reported by the API. You can try to capture a debug log from the three dot menu in the Miele card in integrations page. Start the debug, wait a minute and then start your appliance and then turn it off after a couple of minutes. With a little luck the log might reveal the cause of the problem.

**Comment by AtrejaAlwinnen** [comment]
I started the dishwasher again, but this time for the first time the sensor did not record a spike. I'll take a closer look at it over the next few days. Nevertheless, I have created a debug log and post it here, although nothing unusual happened this time.
[home-assistant_miele_2023-05-21T17-29-12.986Z.log](https://github.com/astrandb/miele/files/11525169/home-assistant_miele_2023-05-21T17-29-12.986Z.log)
[config_entry-miele-e0089fa20e4379770b39460eae7fa5e9.json.txt](https://github.com/astrandb/miele/files/11525170/config_entry-miele-e0089fa20e4379770b39460eae7fa5e9.json.txt)
![waterconsumption3](https://github.com/astrandb/miele/assets/72468128/e47cecd5-5ed9-46d1-97ba-c0191f1bf7b3)

**Comment by aturri** [comment]
Hi @AtrejaAlwinnen,
Can you check the reported state of appliance status sensor and of energy consumption sensor at the time of that spike?

The only assumption that this integration makes for water/energy sensors is to report 0 when appliance is in status off, on (idle), programmed, waiting to start. This because Miele API returns a null eco-feedback object in these cases and value 0 is used to reset the cycle of total increasing sensors on HA.
This has the side effect that, if you turn off the appliance and then you turn it on again while it is running a program, you get that spike. But you should get the same behaviour also on energy consumption sensor. If you set appliance in paused state, you should get normal behaviour instead.

Another possibility is that Miele API reports 0 for some unknown reason. In the past it happened that it randomly reported null eco-feedback object when the appliance was running, but it's a lot of time that I don't see this, so I think it has been fixed.

Andrea

**Comment by AtrejaAlwinnen** [comment]
Hi aturri,
the spikes also appear in the power consumption sensor. I hadn't noticed that until now.
When the dishwasher was started for the second time yesterday, when there was no spike in water consumption, there was also no spike in power consumption.
The sipkes occur exactly at the time when the appliance status changes from off to on.
![Stromverbrauvh](https://github.com/astrandb/miele/assets/72468128/5b1a0b33-adc6-493e-8d27-0e61cecfe726)

**Comment by aturri** [comment]
Hi @AtrejaAlwinnen, 
Can you provide the history graph of these sensors at the time of spike?
- appliance status sensor
- appliance switch 
- water/energy consumption

Like this: 
![image](https://github.com/astrandb/miele/assets/6987093/efd8d065-2978-4599-8e18-de5d1f23c4b5)

So I can understand what happened 😁 

Thanks
Andrea

**Comment by AtrejaAlwinnen** [comment]
Hi Andrea,
thanks for looking at this
here is a screenshot of the sensors:
![zusammanfassung](https://github.com/astrandb/miele/assets/72468128/9913b5e6-89ee-4f71-88b6-bbdb0789a5d6)

**Comment by aturri** [comment]
Hi @AtrejaAlwinnen,
this confirms what I thought: the appliance has been turned off while it was running a program. Then, it has been turned on and its status went from "off" to "running". Normally, the appliance follows "off" -> "on" -> "programmed" -> "running".
I think that this strange behaviour is caused by the fact that when appliance is turned on again, on Miele API, the previous consumption is reported for a while (spike) and then it starts back from 0. If this is true, there is no way to filter out the spike on HA integration and it's a problem related to API.

In order to confirm this, you should try doing the following:
- start a new program, let water come in and consume some energy
- turn appliance off and get device diagnostic data log (n.1)
- turn appliance on (we should see the spike)
- get device diagnostic data log as the consumption goes to 0 (n.2)
- get device diagnostic data log as the consumption increases (n.3)

This should prove that the consumption is back to 0 when appliance is restarted.

Andrea

**Comment by AtrejaAlwinnen** [comment]
I ran into a few problems while trying to follow the steps.
1. I started a program and waited a bit.
2. Disabled the Miele integration but could no longer download diagnostic data from the dishwasher.
3. Miele integration activated again but the dishwasher is not connected. It is also offline in the Miele app.

I'll try again tomorrow with the washing machine.

Many thanks for the help if the problem is that e.g. Home Assistant shouldn't be restarted while the dishwasher or washing machine is running, that's absolutely fine for me. :)

**Comment by mundschenk-at** [comment]
@AtrejaAlwinnen Why did you disable the integration?

**Comment by mundschenk-at** [comment]
No, "appliance" means the device. "Household appliances" is the collective term for dishwashers, washing machines etc.

**Comment by AtrejaAlwinnen** [comment]
So, the dishwasher is running again. 
I was unable to reproduce the spike issue again. I've tried several times with both devices, but now everything works fine. Maybe it really had something to do with the fact that I restarted HA several times when setting up the sensors, which caused spikes in the sensor process.

Many thanks to everyone who took the time and made the effort to look into this.

**Comment by slovdahl** [comment]
This is a long-standing problem with the Miele API and/or devices. 😒

Up until today I have been using https://github.com/HomeAssistant-Mods/home-assistant-miele for getting my Miele devices into HA, but for some reason the integration has stopped working for me, so today I installed this one instead.

I initially implemented [energy](https://github.com/HomeAssistant-Mods/home-assistant-miele/pull/59) and [water](https://github.com/HomeAssistant-Mods/home-assistant-miele/pull/63) consumption sensors in the other integration. But as I seem to be consistently hit by this issue, I also spent a considerable amount of time debugging it in https://github.com/HomeAssistant-Mods/home-assistant-miele/pull/69. I even tried to contact Miele about it but never got any response. Back then, part of the problem was the API returning `null` from time to time while a program was running, but it's nice to hear that that problem might have been solved.

The fix in https://github.com/HomeAssistant-Mods/home-assistant-miele/pull/69 worked around the issues most of the time ~1.5 years ago, but I think some HA integration refactoring or Miele API change made it ineffective and it started causing problems more often again some time ago.

Two screenshots from today with two spikes for my dishwasher using this integration, the first one for energy and the second one for water consumption:

<img width="1379" alt="image" src="https://github.com/astrandb/miele/assets/1417619/49442595-35dc-40fa-8282-a07e5958c71b">

<img width="1379" alt="image" src="https://github.com/astrandb/miele/assets/1417619/eb0b2303-0d91-44a4-ade1-257e72b126f4">
