### ISSUE TITLE
Friendly names of entities and device types should be translated

### ISSUE THREAD

**Issue by mundschenk-at** [astrandb/miele#31]
### Feature request

The friendly names of entitites (and maybe the entities themselves) should be translated, and also the device types.

### What version of the integration are you using?

miele-0.10

**Comment by astrandb** [comment]
There is no built-in support for translation in the core/back-end of Home Assistant.

Names of devices and entities (and areas) are not translatable in frontend of Home Assistant. They are assigned permanent names when they are created. Statuses of different variants can be translated at the user's discretion by selecting language in the personal profile. This means that you cannot change Fridge to Kühlschrank after the enties are created.

The only way, which might be OK, is to select one of the languages that are supported by Miele at initial setup. The devices and entities will then be created with the localized name.  But there is no way back, except to reinstall the integration. There might also be  terms that are not localized properly due to imperfections in in Miele's API. E.g. there is no support for Swedish, even though the Swedish population is about the same as Denmark and Norway added together.

We must still keep the internal representation to a single language (English). Otherwise e.g. automations might not work properly if a user changes language in the frontend.

Let's keep this FR on the whish-list for the time beeing.

**Comment by mundschenk-at** [comment]
Yes, I meant when they are initially created. I assumed it was possible, but now that I think about it, I'm not sure if the actual HA installation has a locale/language set or only my user-specific frontend. If it's just the frontend, forget about it and just use English. Messing around with the Miele languages would be too confusing in the long run.
