### ISSUE TITLE
fridge freezer combination  -- freezer temperature not showen

### ISSUE THREAD

**Issue by Volti-Ba** [astrandb/miele#81]
### The problem

The freezer zone are not show in the integrations.
The temperature and temp. target  is showen in the zone 2, but is disabled. i activated manually for test.
There is only the thermostat to set temp. for the fidge 

I take a log.file and screenshots for better understanding
Sorry is first issue on github  ;-)
I hope you undstand me

[miele-f58686a74689bea6995f561fa181da25-Fridge freezer-9ef07a853f63806680f0d320f5f52f60.json.txt](https://github.com/astrandb/miele/files/8404000/miele-f58686a74689bea6995f561fa181da25-Fridge.freezer-9ef07a853f63806680f0d320f5f52f60.json.txt)
![Hass-Miele](https://user-images.githubusercontent.com/56272434/161416873-d7a7eefe-ecb0-45e0-8a2b-c437828f81ed.JPG)
![miele_Freezer](https://user-images.githubusercontent.com/56272434/161416879-3677ccc5-d505-486f-b51c-c1909fa45c07.JPG)
.

### Version of miele integration having the issue?

0.0.19

### Version of Home Assistant Core having the issue?

2022.3.8

**Comment by astrandb** [comment]
@Volti-Ba Thank you for reporting this bug. I will look into it.

**Comment by astrandb** [comment]
@Volti-Ba The problem with missing climate entity for zone 2 (freezer) is identified and fixed in the code.

I need clarification regarding the sensors for `Temperature zone 2` and `Target temperature zone 2`:

It is intended that they are disabled by default and that you have to enable them manually. They should start to work approximately 30 seconds after you enabling them. You may have to refresh the browser cache after waiting the 30 seconds.

Are they working as described?

I can try to fix so they are enabled automatically for this device type but that will be in a later version.

You can test the fix for the climate entity by downloading the version `main` (at the bottom of version list) in HACS.

**Comment by Volti-Ba** [comment]
Yes, the  sensors work after i enable them manually.

Thank you.

![miele_temp_Zone2](https://user-images.githubusercontent.com/56272434/161435826-ef54f52f-f216-4c7b-8fa3-f4c275fdfd68.JPG)

**Comment by Volti-Ba** [comment]
Works good for me, Thank you!
